name: 'Terraform'

on:
#   push:
#     branches:
#       - main
    pull_request:
        
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    # Add permissions for OIDC
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: environments/dev

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: environments/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: environments/dev

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: environments/dev